[program:kilang-ffmpeg-streamer]
command=php /var/www/kilang-cctv/artisan cctv:streamer --non-interactive
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/kilang-ffmpeg-streamer.log
environment=APP_ENV=production,APP_BASE_PATH="/var/www/kilang-cctv"