[program:kilang-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/kilang-cctv/artisan queue:work --sleep=1 --tries=3 --max-time=3600
autostart=true
autorestart=true
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/kilang-queue.log
environment=APP_ENV=production,APP_BASE_PATH="/var/www/kilang-cctv"

[program:kilang-schedule]
command=php /var/www/kilang-cctv/artisan schedule:work
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/kilang-schedule.log
environment=APP_ENV=production,APP_BASE_PATH="/var/www/kilang-cctv"